openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: Contact Name
    email: contact@example.com
    url: https://example.com/
tags:
  - name: Metadata
    description: Metadata related requests
paths:
  /hello/{id}:
    parameters:
    - name: id
      description: ID of the thing to get
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: find_thing
      description: Get one thing
      tags: ["Metadata"]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: [hello, id]
                  properties:
                    hello:
                      type: string
                    id:
                      type: string
  /hello:
    get:
      operationId: find_things
      description: Get multiple things
      tags: ["Metadata"]
      parameters:
      - name: filter
        description: filter things
        in: query
        required: false
        schema:
          type: object
          required: [id]
          properties:
            id:
              type: string
              description: Comma separated list of thing-IDs

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [hello]
                properties:
                  hello:
                    type: string
        default:
          description: Error response

    post:
      operationId: create_thing
      description: Create a thing
      tags: ["Metadata"]
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [hello]
                properties:
                  hello:
                    type: string
