AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "*.gemspec"
Metrics/MethodLength:
  Max: 20
