AllCops:
  TargetRubyVersion: 2.6
Documentation:
  Enabled: false
BlockLength:
  Exclude:
  - 'spec/**/*.rb'
  - '*.gemspec'
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
